/* Single source of truth for the /funding map. funding.json is hand-seeded for
 * now (plan 1) and regenerated by experiments/funding/build_funding.py (plan 2);
 * this module types it and re-exports — mirrors src/data/companies.ts.
 *
 * Validation lives in funding-validate.ts (build-time only — imported from
 * FundingGraph.astro frontmatter). Never import companies.json or run
 * validation here: this module is bundled into client JS and must stay lean.
 *
 * The private overlay (pipeline stage + warm paths) is NOT imported here — it is
 * read from private/funding-overlay.json in FundingGraph.astro, dev-only. */

import rawData from "./funding.json";
import type { FundingData, FundingNode, FundingEdge, FundingMeta } from "./funding-types";

export * from "./funding-types";

const data = rawData as unknown as FundingData;
export const fundingNodes: FundingNode[] = data.nodes;
export const fundingEdges: FundingEdge[] = data.edges;
export const fundingMeta: FundingMeta = data.meta;
